import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'

if (process.env.NODE_ENV === 'development') {
  import('../mocks/worker').then(({ setupMocks }) => {
    setupMocks()
  })
}

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
